# Source of widget translations. Run: python3 scripts/i18n-source.py  -> public/i18n/<lang>.json
# Keys missing from a language fall back to English in the widget.
import json, os
K = """title open close language reset statement hide hidden poweredBy sectionProfiles sectionContent sectionColor sectionOrientation sectionTools on off
p_seizure p_seizure_d p_vision p_vision_d p_adhd p_adhd_d p_cognitive p_cognitive_d p_keyboard p_keyboard_d p_blind p_blind_d p_dyslexia p_dyslexia_d p_elderly p_elderly_d p_motor p_motor_d p_colorblind p_colorblind_d
fontSize lineHeight letterSpacing wordSpacing textAlign readableFont dyslexiaFont highlightTitles highlightLinks textMagnifier contrast saturation customColors textColor titleColor bgColor bigCursor readingGuide readingMask stopAnimations hideImages muteSounds highlightFocus highlightHover imageDescriptions keyboardNav pageStructure screenReader readPage voiceNav virtualKeyboard dictionary
l_left l_center l_right l_justify l_dark l_light l_high l_invert l_low l_mono l_black l_white l_normal l_fast l_slow
headings landmarks links none back noAlt listening dictLoading dictNotFound dictMore skipToContent opensNewTab stop space enter shift backspace""".split()

T = {
'es': """Accesibilidad|Abrir menú de accesibilidad (Alt+A)|Cerrar|Idioma|Restablecer ajustes|Declaración de accesibilidad|Ocultar interfaz|Menú de accesibilidad oculto. Pulse Alt+A para abrirlo de nuevo.|Con tecnología de|Perfiles de accesibilidad|Ajustes de contenido|Ajustes de color|Orientación y navegación|Herramientas de asistencia|Activado|Desactivado
Apto para epilepsia|Detiene destellos y reduce el color|Discapacidad visual|Mejora los elementos visuales|Apto para TDAH|Menos distracción, más concentración|Discapacidad cognitiva|Ayuda a leer y concentrarse|Navegación con teclado|Use el sitio con el teclado|Personas ciegas|Soporte de lector de pantalla|Apto para dislexia|Fuente y espaciado más legibles|Personas mayores|Texto y cursor más grandes|Discapacidad motriz|Señalar y escribir más fácil|Daltonismo|Colores y enlaces más marcados
Tamaño del texto|Altura de línea|Espaciado de letras|Espaciado de palabras|Alineación del texto|Fuente legible|Fuente para dislexia|Resaltar títulos|Resaltar enlaces|Lupa de texto|Contraste|Saturación|Colores personalizados|Texto|Títulos|Fondo|Cursor grande|Guía de lectura|Máscara de lectura|Detener animaciones|Ocultar imágenes|Silenciar sonidos|Resaltar foco|Resaltar al pasar|Descripciones de imágenes|Atajos de teclado|Estructura de la página|Texto a voz|Leer la página en voz alta|Navegación por voz|Teclado virtual|Diccionario
Izquierda|Centro|Derecha|Justificado|Oscuro|Claro|Alto|Invertido|Baja|Monocromo|Negro|Blanco|Normal|Rápido|Lento
Encabezados|Regiones|Enlaces|No se encontró nada|Atrás|Sin descripción disponible|Escuchando…|Buscando…|No se encontró definición.|Más en Wikcionario|Saltar al contenido principal|(se abre en una pestaña nueva)|Detener|Espacio|Intro|Mayús|Borrar""",
'fr': """Accessibilité|Ouvrir le menu d'accessibilité (Alt+A)|Fermer|Langue|Réinitialiser|Déclaration d'accessibilité|Masquer l'interface|Menu d'accessibilité masqué. Appuyez sur Alt+A pour le rouvrir.|Propulsé par|Profils d'accessibilité|Réglages du contenu|Réglages des couleurs|Orientation et navigation|Outils d'assistance|Activé|Désactivé
Sans risque d'épilepsie|Supprime les flashs et réduit les couleurs|Malvoyance|Améliore les visuels du site|Adapté au TDAH|Moins de distractions, plus de concentration|Handicap cognitif|Aide à la lecture et à la concentration|Navigation au clavier|Utiliser le site au clavier|Personnes aveugles|Prise en charge du lecteur d'écran|Adapté à la dyslexie|Police et espacement plus lisibles|Seniors|Texte et curseur plus grands|Handicap moteur|Pointer et saisir plus facilement|Daltonisme|Couleurs et liens plus marqués
Taille du texte|Hauteur de ligne|Espacement des lettres|Espacement des mots|Alignement du texte|Police lisible|Police dyslexie|Surligner les titres|Surligner les liens|Loupe de texte|Contraste|Saturation|Couleurs personnalisées|Texte|Titres|Arrière-plan|Grand curseur|Guide de lecture|Masque de lecture|Arrêter les animations|Masquer les images|Couper le son|Surligner le focus|Surligner au survol|Descriptions des images|Raccourcis clavier|Structure de la page|Synthèse vocale|Lire la page à voix haute|Navigation vocale|Clavier virtuel|Dictionnaire
Gauche|Centre|Droite|Justifié|Sombre|Clair|Élevé|Inversé|Faible|Monochrome|Noir|Blanc|Normal|Rapide|Lent
Titres|Repères|Liens|Aucun résultat|Retour|Aucune description disponible|Écoute…|Recherche…|Aucune définition trouvée.|Plus sur le Wiktionnaire|Aller au contenu principal|(s'ouvre dans un nouvel onglet)|Arrêter|Espace|Entrée|Maj|Effacer""",
'de': """Barrierefreiheit|Barrierefreiheitsmenü öffnen (Alt+A)|Schließen|Sprache|Einstellungen zurücksetzen|Erklärung zur Barrierefreiheit|Oberfläche ausblenden|Menü ausgeblendet. Mit Alt+A wieder öffnen.|Bereitgestellt von|Barrierefreiheitsprofile|Inhaltsanpassungen|Farbanpassungen|Orientierung & Navigation|Hilfswerkzeuge|An|Aus
Epilepsiesicher|Stoppt Blitze und reduziert Farben|Sehbehinderung|Verbessert die Darstellung|ADHS-freundlich|Weniger Ablenkung, mehr Fokus|Kognitive Beeinträchtigung|Hilft beim Lesen und Konzentrieren|Tastaturnavigation|Website per Tastatur bedienen|Blinde Nutzer|Screenreader-Unterstützung|Legasthenie-freundlich|Lesbarere Schrift und Abstände|Ältere Menschen|Größerer Text und Cursor|Motorische Einschränkung|Leichteres Zeigen und Tippen|Farbenblindheit|Kräftigere Farben und Links
Textgröße|Zeilenhöhe|Buchstabenabstand|Wortabstand|Textausrichtung|Lesbare Schrift|Legasthenie-Schrift|Überschriften hervorheben|Links hervorheben|Textlupe|Kontrast|Sättigung|Eigene Farben|Text|Überschriften|Hintergrund|Großer Cursor|Leselineal|Lesemaske|Animationen stoppen|Bilder ausblenden|Ton aus|Fokus hervorheben|Hover hervorheben|Bildbeschreibungen|Tastenkürzel|Seitenstruktur|Vorlesen|Seite vorlesen|Sprachsteuerung|Bildschirmtastatur|Wörterbuch
Links|Zentriert|Rechts|Blocksatz|Dunkel|Hell|Hoch|Invertiert|Niedrig|Schwarzweiß|Schwarz|Weiß|Normal|Schnell|Langsam
Überschriften|Bereiche|Links|Nichts gefunden|Zurück|Keine Beschreibung verfügbar|Hört zu…|Suche…|Keine Definition gefunden.|Mehr im Wiktionary|Zum Hauptinhalt springen|(öffnet in neuem Tab)|Stopp|Leertaste|Eingabe|Umschalt|Löschen""",
'it': """Accessibilità|Apri il menu accessibilità (Alt+A)|Chiudi|Lingua|Ripristina impostazioni|Dichiarazione di accessibilità|Nascondi interfaccia|Menu nascosto. Premi Alt+A per riaprirlo.|Realizzato con|Profili di accessibilità|Regolazioni del contenuto|Regolazioni del colore|Orientamento e navigazione|Strumenti di assistenza|Attivo|Disattivo
Sicuro per l'epilessia|Ferma i lampeggi e riduce i colori|Ipovisione|Migliora la resa visiva|Adatto all'ADHD|Meno distrazioni, più concentrazione|Disabilità cognitiva|Aiuta a leggere e concentrarsi|Navigazione da tastiera|Usa il sito con la tastiera|Utenti non vedenti|Supporto lettore di schermo|Adatto alla dislessia|Font e spaziatura più leggibili|Anziani|Testo e cursore più grandi|Disabilità motoria|Puntare e digitare più facilmente|Daltonismo|Colori e link più evidenti
Dimensione testo|Altezza riga|Spaziatura lettere|Spaziatura parole|Allineamento testo|Font leggibile|Font per dislessia|Evidenzia titoli|Evidenzia link|Lente sul testo|Contrasto|Saturazione|Colori personalizzati|Testo|Titoli|Sfondo|Cursore grande|Guida di lettura|Maschera di lettura|Ferma animazioni|Nascondi immagini|Disattiva audio|Evidenzia focus|Evidenzia al passaggio|Descrizioni immagini|Scorciatoie da tastiera|Struttura della pagina|Sintesi vocale|Leggi la pagina ad alta voce|Navigazione vocale|Tastiera virtuale|Dizionario
Sinistra|Centro|Destra|Giustificato|Scuro|Chiaro|Alto|Invertito|Bassa|Monocromatico|Nero|Bianco|Normale|Veloce|Lento
Intestazioni|Aree|Link|Nessun risultato|Indietro|Nessuna descrizione disponibile|In ascolto…|Ricerca…|Nessuna definizione trovata.|Altro su Wikizionario|Vai al contenuto principale|(si apre in una nuova scheda)|Stop|Spazio|Invio|Maiusc|Cancella""",
'pt': """Acessibilidade|Abrir menu de acessibilidade (Alt+A)|Fechar|Idioma|Redefinir configurações|Declaração de acessibilidade|Ocultar interface|Menu oculto. Pressione Alt+A para abrir novamente.|Desenvolvido por|Perfis de acessibilidade|Ajustes de conteúdo|Ajustes de cor|Orientação e navegação|Ferramentas assistivas|Ativado|Desativado
Seguro para epilepsia|Para flashes e reduz cores|Deficiência visual|Melhora o visual do site|Amigável para TDAH|Menos distração, mais foco|Deficiência cognitiva|Ajuda a ler e focar|Navegação por teclado|Use o site pelo teclado|Pessoas cegas|Suporte a leitor de tela|Amigável para dislexia|Fonte e espaçamento mais legíveis|Idosos|Texto e cursor maiores|Deficiência motora|Apontar e digitar com facilidade|Daltonismo|Cores e links mais fortes
Tamanho do texto|Altura da linha|Espaçamento de letras|Espaçamento de palavras|Alinhamento do texto|Fonte legível|Fonte para dislexia|Destacar títulos|Destacar links|Lupa de texto|Contraste|Saturação|Cores personalizadas|Texto|Títulos|Fundo|Cursor grande|Guia de leitura|Máscara de leitura|Parar animações|Ocultar imagens|Silenciar sons|Destacar foco|Destacar ao passar|Descrições de imagens|Atalhos de teclado|Estrutura da página|Texto para fala|Ler a página em voz alta|Navegação por voz|Teclado virtual|Dicionário
Esquerda|Centro|Direita|Justificado|Escuro|Claro|Alto|Invertido|Baixa|Monocromático|Preto|Branco|Normal|Rápido|Lento
Títulos|Regiões|Links|Nada encontrado|Voltar|Sem descrição disponível|Ouvindo…|Procurando…|Nenhuma definição encontrada.|Mais no Wikcionário|Pular para o conteúdo principal|(abre em nova aba)|Parar|Espaço|Enter|Shift|Apagar""",
'nl': """Toegankelijkheid|Toegankelijkheidsmenu openen (Alt+A)|Sluiten|Taal|Instellingen herstellen|Toegankelijkheidsverklaring|Interface verbergen|Menu verborgen. Druk op Alt+A om het weer te openen.|Mogelijk gemaakt door|Toegankelijkheidsprofielen|Inhoud aanpassen|Kleuren aanpassen|Oriëntatie & navigatie|Hulpmiddelen|Aan|Uit
Epilepsieveilig|Stopt flitsen en vermindert kleur|Visuele beperking|Verbetert de weergave|ADHD-vriendelijk|Minder afleiding, meer focus|Cognitieve beperking|Helpt bij lezen en concentreren|Toetsenbordnavigatie|Gebruik de site met het toetsenbord|Blinde gebruikers|Ondersteuning voor schermlezers|Dyslexievriendelijk|Beter leesbaar lettertype en spatiëring|Ouderen|Grotere tekst en cursor|Motorische beperking|Makkelijker aanwijzen en typen|Kleurenblind|Sterkere kleuren en links
Tekstgrootte|Regelhoogte|Letterafstand|Woordafstand|Tekstuitlijning|Leesbaar lettertype|Dyslexie-lettertype|Koppen markeren|Links markeren|Tekstvergroter|Contrast|Verzadiging|Eigen kleuren|Tekst|Koppen|Achtergrond|Grote cursor|Leesliniaal|Leesmasker|Animaties stoppen|Afbeeldingen verbergen|Geluid dempen|Focus markeren|Hover markeren|Afbeeldingsbeschrijvingen|Sneltoetsen|Paginastructuur|Tekst naar spraak|Pagina voorlezen|Spraaknavigatie|Virtueel toetsenbord|Woordenboek
Links|Midden|Rechts|Uitgevuld|Donker|Licht|Hoog|Omgekeerd|Laag|Zwart-wit|Zwart|Wit|Normaal|Snel|Langzaam
Koppen|Regio's|Links|Niets gevonden|Terug|Geen beschrijving beschikbaar|Luisteren…|Zoeken…|Geen definitie gevonden.|Meer op WikiWoordenboek|Naar hoofdinhoud|(opent in nieuw tabblad)|Stop|Spatie|Enter|Shift|Wissen""",
'pl': """Dostępność|Otwórz menu dostępności (Alt+A)|Zamknij|Język|Resetuj ustawienia|Deklaracja dostępności|Ukryj interfejs|Menu ukryte. Naciśnij Alt+A, aby je otworzyć.|Obsługiwane przez|Profile dostępności|Dostosowanie treści|Dostosowanie kolorów|Orientacja i nawigacja|Narzędzia wspierające|Wł.|Wył.
Bezpieczny dla epilepsji|Zatrzymuje błyski i ogranicza kolory|Niedowidzenie|Poprawia wygląd strony|Przyjazny dla ADHD|Mniej rozproszeń, więcej skupienia|Niepełnosprawność poznawcza|Pomaga w czytaniu i skupieniu|Nawigacja klawiaturą|Obsługa strony klawiaturą|Osoby niewidome|Obsługa czytnika ekranu|Przyjazny dla dysleksji|Czytelniejsza czcionka i odstępy|Seniorzy|Większy tekst i kursor|Niepełnosprawność ruchowa|Łatwiejsze wskazywanie i pisanie|Daltonizm|Mocniejsze kolory i linki
Rozmiar tekstu|Wysokość linii|Odstępy liter|Odstępy słów|Wyrównanie tekstu|Czytelna czcionka|Czcionka dla dysleksji|Wyróżnij nagłówki|Wyróżnij linki|Lupa tekstu|Kontrast|Nasycenie|Własne kolory|Tekst|Nagłówki|Tło|Duży kursor|Linijka do czytania|Maska do czytania|Zatrzymaj animacje|Ukryj obrazy|Wycisz dźwięki|Wyróżnij fokus|Wyróżnij po najechaniu|Opisy obrazów|Skróty klawiszowe|Struktura strony|Czytanie tekstu|Przeczytaj stronę na głos|Nawigacja głosowa|Klawiatura ekranowa|Słownik
Do lewej|Wyśrodkuj|Do prawej|Wyjustuj|Ciemny|Jasny|Wysoki|Odwrócony|Niskie|Monochromatyczny|Czarny|Biały|Normalnie|Szybko|Wolno
Nagłówki|Obszary|Linki|Nic nie znaleziono|Wstecz|Brak opisu|Słucham…|Wyszukiwanie…|Nie znaleziono definicji.|Więcej w Wikisłowniku|Przejdź do treści głównej|(otwiera się w nowej karcie)|Zatrzymaj|Spacja|Enter|Shift|Usuń""",
'tr': """Erişilebilirlik|Erişilebilirlik menüsünü aç (Alt+A)|Kapat|Dil|Ayarları sıfırla|Erişilebilirlik beyanı|Arayüzü gizle|Menü gizlendi. Tekrar açmak için Alt+A'ya basın.|Destekleyen|Erişilebilirlik profilleri|İçerik ayarları|Renk ayarları|Yönlendirme ve gezinme|Yardımcı araçlar|Açık|Kapalı
Epilepsi için güvenli|Yanıp sönmeleri durdurur, rengi azaltır|Görme engelli|Görselleri iyileştirir|DEHB dostu|Daha az dikkat dağınıklığı|Bilişsel engel|Okuma ve odaklanmaya yardımcı|Klavye ile gezinme|Siteyi klavyeyle kullanın|Görme engelli kullanıcılar|Ekran okuyucu desteği|Disleksi dostu|Daha okunaklı yazı ve aralık|Yaşlılar|Daha büyük yazı ve imleç|Motor engelli|Daha kolay işaretleme ve yazma|Renk körlüğü|Daha güçlü renkler ve bağlantılar
Yazı boyutu|Satır yüksekliği|Harf aralığı|Kelime aralığı|Metin hizalama|Okunaklı yazı tipi|Disleksi yazı tipi|Başlıkları vurgula|Bağlantıları vurgula|Metin büyüteci|Kontrast|Doygunluk|Özel renkler|Metin|Başlıklar|Arka plan|Büyük imleç|Okuma kılavuzu|Okuma maskesi|Animasyonları durdur|Görselleri gizle|Sesleri kapat|Odağı vurgula|Üzerine gelineni vurgula|Görsel açıklamaları|Klavye kısayolları|Sayfa yapısı|Metin okuma|Sayfayı sesli oku|Sesli gezinme|Sanal klavye|Sözlük
Sol|Orta|Sağ|İki yana|Koyu|Açık|Yüksek|Ters|Düşük|Siyah beyaz|Siyah|Beyaz|Normal|Hızlı|Yavaş
Başlıklar|Bölgeler|Bağlantılar|Hiçbir şey bulunamadı|Geri|Açıklama yok|Dinleniyor…|Aranıyor…|Tanım bulunamadı.|Vikisözlük'te daha fazlası|Ana içeriğe geç|(yeni sekmede açılır)|Durdur|Boşluk|Enter|Shift|Sil""",
'ru': """Доступность|Открыть меню доступности (Alt+A)|Закрыть|Язык|Сбросить настройки|Заявление о доступности|Скрыть интерфейс|Меню скрыто. Нажмите Alt+A, чтобы открыть его снова.|Работает на|Профили доступности|Настройки контента|Настройки цвета|Ориентация и навигация|Вспомогательные инструменты|Вкл.|Выкл.
Безопасно при эпилепсии|Убирает вспышки и снижает цвет|Слабое зрение|Улучшает отображение сайта|Для СДВГ|Меньше отвлечений, больше фокуса|Когнитивные нарушения|Помогает читать и сосредоточиться|Навигация с клавиатуры|Управление сайтом с клавиатуры|Незрячие пользователи|Поддержка экранного диктора|Для дислексии|Более читаемый шрифт и интервалы|Пожилые люди|Крупный текст и курсор|Нарушения моторики|Проще наводить и печатать|Дальтонизм|Более яркие цвета и ссылки
Размер текста|Высота строки|Межбуквенный интервал|Межсловный интервал|Выравнивание текста|Читаемый шрифт|Шрифт для дислексии|Выделить заголовки|Выделить ссылки|Лупа текста|Контраст|Насыщенность|Свои цвета|Текст|Заголовки|Фон|Большой курсор|Линейка чтения|Маска чтения|Остановить анимацию|Скрыть изображения|Выключить звук|Выделить фокус|Выделять при наведении|Описания изображений|Горячие клавиши|Структура страницы|Озвучивание текста|Прочитать страницу вслух|Голосовая навигация|Экранная клавиатура|Словарь
Слева|По центру|Справа|По ширине|Тёмный|Светлый|Высокий|Инверсия|Низкая|Монохром|Чёрный|Белый|Обычно|Быстро|Медленно
Заголовки|Области|Ссылки|Ничего не найдено|Назад|Описание отсутствует|Слушаю…|Поиск…|Определение не найдено.|Подробнее в Викисловаре|Перейти к основному содержанию|(открывается в новой вкладке)|Стоп|Пробел|Ввод|Shift|Удалить""",
'ar': """إمكانية الوصول|فتح قائمة إمكانية الوصول (Alt+A)|إغلاق|اللغة|إعادة ضبط الإعدادات|بيان إمكانية الوصول|إخفاء الواجهة|تم إخفاء القائمة. اضغط Alt+A لفتحها مجددًا.|مدعوم من|ملفات إمكانية الوصول|تعديلات المحتوى|تعديلات الألوان|التوجيه والتنقل|أدوات مساعدة|تشغيل|إيقاف
آمن لمرضى الصرع|يوقف الوميض ويقلل الألوان|ضعف البصر|يحسّن مظهر الموقع|مناسب لفرط الحركة|تشتت أقل وتركيز أكثر|إعاقة إدراكية|يساعد على القراءة والتركيز|التنقل بلوحة المفاتيح|استخدم الموقع بلوحة المفاتيح|المستخدمون المكفوفون|دعم قارئ الشاشة|مناسب لعسر القراءة|خط وتباعد أسهل للقراءة|كبار السن|نص ومؤشر أكبر|إعاقة حركية|تأشير وكتابة أسهل|عمى الألوان|ألوان وروابط أوضح
حجم النص|ارتفاع السطر|تباعد الأحرف|تباعد الكلمات|محاذاة النص|خط مقروء|خط عسر القراءة|تمييز العناوين|تمييز الروابط|مكبّر النص|التباين|التشبع|ألوان مخصصة|النص|العناوين|الخلفية|مؤشر كبير|دليل القراءة|قناع القراءة|إيقاف الحركة|إخفاء الصور|كتم الأصوات|تمييز التركيز|تمييز عند المرور|أوصاف الصور|اختصارات لوحة المفاتيح|بنية الصفحة|تحويل النص إلى كلام|قراءة الصفحة بصوت عالٍ|التنقل الصوتي|لوحة مفاتيح افتراضية|القاموس
يسار|وسط|يمين|ضبط|داكن|فاتح|عالٍ|معكوس|منخفض|أحادي اللون|أسود|أبيض|عادي|سريع|بطيء
العناوين|المعالم|الروابط|لم يتم العثور على شيء|رجوع|لا يوجد وصف|جارٍ الاستماع…|جارٍ البحث…|لم يتم العثور على تعريف.|المزيد في ويكاموس|تخطَّ إلى المحتوى الرئيسي|(يفتح في علامة تبويب جديدة)|إيقاف|مسافة|إدخال|Shift|حذف""",
'he': """נגישות|פתיחת תפריט הנגישות (Alt+A)|סגירה|שפה|איפוס הגדרות|הצהרת נגישות|הסתרת הממשק|התפריט הוסתר. לחצו Alt+A כדי לפתוח אותו שוב.|מופעל על ידי|פרופילי נגישות|התאמות תוכן|התאמות צבע|התמצאות וניווט|כלי עזר|פעיל|כבוי
בטוח לאפילפסיה|עוצר הבהובים ומפחית צבע|לקות ראייה|משפר את התצוגה|מותאם להפרעת קשב|פחות הסחות, יותר ריכוז|לקות קוגניטיבית|מסייע בקריאה ובריכוז|ניווט במקלדת|שימוש באתר עם מקלדת|משתמשים עיוורים|תמיכה בקורא מסך|מותאם לדיסלקציה|גופן ומרווחים קריאים יותר|גיל הזהב|טקסט וסמן גדולים יותר|לקות מוטורית|הצבעה והקלדה קלות יותר|עיוורון צבעים|צבעים וקישורים בולטים
גודל טקסט|גובה שורה|מרווח אותיות|מרווח מילים|יישור טקסט|גופן קריא|גופן לדיסלקציה|הדגשת כותרות|הדגשת קישורים|זכוכית מגדלת לטקסט|ניגודיות|רוויה|צבעים מותאמים|טקסט|כותרות|רקע|סמן גדול|סרגל קריאה|מסכת קריאה|עצירת אנימציות|הסתרת תמונות|השתקת צלילים|הדגשת פוקוס|הדגשה במעבר עכבר|תיאורי תמונות|קיצורי מקלדת|מבנה הדף|הקראת טקסט|הקראת הדף|ניווט קולי|מקלדת וירטואלית|מילון
שמאל|מרכז|ימין|מיושר|כהה|בהיר|גבוהה|הפוך|נמוכה|שחור־לבן|שחור|לבן|רגיל|מהיר|איטי
כותרות|אזורים|קישורים|לא נמצא דבר|חזרה|אין תיאור זמין|מאזין…|מחפש…|לא נמצאה הגדרה.|עוד בוויקימילון|דילוג לתוכן הראשי|(נפתח בכרטיסייה חדשה)|עצירה|רווח|אנטר|Shift|מחיקה""",
'hi': """सुगम्यता|सुगम्यता मेनू खोलें (Alt+A)|बंद करें|भाषा|सेटिंग्स रीसेट करें|सुगम्यता विवरण|इंटरफ़ेस छिपाएँ|मेनू छिपा दिया गया। फिर से खोलने के लिए Alt+A दबाएँ।|द्वारा संचालित|सुगम्यता प्रोफ़ाइल|सामग्री समायोजन|रंग समायोजन|दिशा और नेविगेशन|सहायक उपकरण|चालू|बंद
मिर्गी के लिए सुरक्षित|चमक रोकता है और रंग कम करता है|दृष्टिबाधित|वेबसाइट के दृश्य बेहतर करता है|ADHD अनुकूल|कम व्यवधान, अधिक ध्यान|संज्ञानात्मक अक्षमता|पढ़ने और ध्यान में मदद|कीबोर्ड नेविगेशन|कीबोर्ड से साइट चलाएँ|दृष्टिहीन उपयोगकर्ता|स्क्रीन रीडर समर्थन|डिस्लेक्सिया अनुकूल|पढ़ने में आसान फ़ॉन्ट और अंतर|वरिष्ठ नागरिक|बड़ा टेक्स्ट और कर्सर|गतिशीलता अक्षमता|आसान पॉइंटिंग और टाइपिंग|रंग अंधता|गहरे रंग और लिंक
टेक्स्ट आकार|पंक्ति ऊँचाई|अक्षर अंतर|शब्द अंतर|टेक्स्ट संरेखण|पठनीय फ़ॉन्ट|डिस्लेक्सिया फ़ॉन्ट|शीर्षक हाइलाइट करें|लिंक हाइलाइट करें|टेक्स्ट आवर्धक|कंट्रास्ट|संतृप्ति|कस्टम रंग|टेक्स्ट|शीर्षक|पृष्ठभूमि|बड़ा कर्सर|पढ़ने की गाइड|पढ़ने का मास्क|एनिमेशन रोकें|चित्र छिपाएँ|ध्वनि बंद करें|फ़ोकस हाइलाइट करें|होवर हाइलाइट करें|चित्र विवरण|कीबोर्ड शॉर्टकट|पेज संरचना|टेक्स्ट से वाणी|पेज पढ़कर सुनाएँ|आवाज़ से नेविगेशन|वर्चुअल कीबोर्ड|शब्दकोश
बाएँ|मध्य|दाएँ|समायोजित|गहरा|हल्का|उच्च|उलटा|कम|एकरंगी|काला|सफ़ेद|सामान्य|तेज़|धीमा
शीर्षक|क्षेत्र|लिंक|कुछ नहीं मिला|वापस|कोई विवरण उपलब्ध नहीं|सुन रहा है…|खोज रहा है…|कोई परिभाषा नहीं मिली।|विक्षनरी पर और|मुख्य सामग्री पर जाएँ|(नए टैब में खुलता है)|रोकें|स्पेस|एंटर|शिफ़्ट|मिटाएँ""",
'zh': """无障碍|打开无障碍菜单 (Alt+A)|关闭|语言|重置设置|无障碍声明|隐藏界面|菜单已隐藏。按 Alt+A 重新打开。|技术支持|无障碍模式|内容调整|颜色调整|定位与导航|辅助工具|开|关
癫痫安全|停止闪烁并降低色彩|视力障碍|增强网站视觉效果|ADHD 友好|减少干扰，更专注|认知障碍|帮助阅读和集中注意力|键盘导航|使用键盘浏览网站|盲人用户|屏幕阅读器支持|阅读障碍友好|更易读的字体和间距|老年人|更大的文字和光标|运动障碍|更容易点击和输入|色盲|更鲜明的颜色和链接
文字大小|行高|字母间距|单词间距|文字对齐|易读字体|阅读障碍字体|突出标题|突出链接|文字放大镜|对比度|饱和度|自定义颜色|文字|标题|背景|大光标|阅读指引|阅读遮罩|停止动画|隐藏图片|静音|突出焦点|突出悬停|图片描述|键盘快捷键|页面结构|文字转语音|朗读页面|语音导航|虚拟键盘|词典
左对齐|居中|右对齐|两端对齐|深色|浅色|高|反色|低|单色|黑色|白色|正常|快|慢
标题|区域|链接|未找到内容|返回|无可用描述|正在聆听…|正在查询…|未找到释义。|在维基词典查看更多|跳到主要内容|（在新标签页中打开）|停止|空格|回车|Shift|删除""",
'ja': """アクセシビリティ|アクセシビリティメニューを開く (Alt+A)|閉じる|言語|設定をリセット|アクセシビリティ方針|インターフェースを隠す|メニューを非表示にしました。Alt+A で再度開けます。|提供元|アクセシビリティプロファイル|コンテンツ調整|色の調整|操作とナビゲーション|支援ツール|オン|オフ
てんかん対策|点滅を止め色を抑える|視覚障害|サイトの見た目を強化|ADHD 向け|気が散りにくく集中しやすい|認知障害|読むことと集中を支援|キーボード操作|キーボードでサイトを操作|視覚障害のある方|スクリーンリーダー対応|ディスレクシア向け|読みやすいフォントと間隔|高齢者向け|大きな文字とカーソル|運動障害|ポイントと入力を簡単に|色覚障害|色とリンクを強調
文字サイズ|行の高さ|文字間隔|単語間隔|文字揃え|読みやすいフォント|ディスレクシア用フォント|見出しを強調|リンクを強調|テキスト拡大鏡|コントラスト|彩度|カスタムカラー|テキスト|見出し|背景|大きなカーソル|読書ガイド|読書マスク|アニメーション停止|画像を隠す|音声をミュート|フォーカスを強調|ホバーを強調|画像の説明|キーボードショートカット|ページ構造|読み上げ|ページを読み上げる|音声ナビゲーション|仮想キーボード|辞書
左揃え|中央|右揃え|両端揃え|ダーク|ライト|高|反転|低|モノクロ|黒|白|標準|速い|遅い
見出し|ランドマーク|リンク|見つかりません|戻る|説明はありません|聞き取り中…|検索中…|定義が見つかりません。|ウィクショナリーで詳しく|メインコンテンツへ移動|（新しいタブで開きます）|停止|スペース|Enter|Shift|削除""",
}

# ---- v1.1 keys (competitor parity features) ----
K2 = """colorBlind contentScale smartContrast readMode talkType signLanguage oversize moveWidget reportProblem reportDesc reportEmail reportSend reportThanks reportFail dictSearch talkListening l_protanopia l_deuteranopia l_tritanopia l_achromatopsia voice srHelp""".split()
T2 = {
'es': "Daltonismo|Escala del contenido|Contraste inteligente|Modo lectura|Hablar y escribir|Lengua de señas (Libras)|Widget grande|Mover widget|Informar un problema|¿Qué problema encontró?|Su correo (opcional)|Enviar|¡Gracias! Su informe se envió al propietario del sitio.|No se pudo enviar el informe. Inténtelo de nuevo.|Buscar una palabra|Hable para escribir en el campo…|Protanopía|Deuteranopía|Tritanopía|Acromatopsia|Voz|Pulse Tab para moverse, Alt+H para encabezados, Control+K para pausar.",
'fr': "Daltonisme|Mise à l'échelle du contenu|Contraste intelligent|Mode lecture|Dicter et écrire|Langue des signes (Libras)|Widget agrandi|Déplacer le widget|Signaler un problème|Quel problème avez-vous rencontré ?|Votre e-mail (facultatif)|Envoyer|Merci ! Votre signalement a été envoyé au propriétaire du site.|Impossible d'envoyer le signalement. Réessayez.|Chercher un mot|Parlez pour écrire dans le champ…|Protanopie|Deutéranopie|Tritanopie|Achromatopsie|Voix|Appuyez sur Tab pour vous déplacer, Alt+H pour les titres, Contrôle+K pour mettre en pause.",
'de': "Farbenblindheit|Inhalt skalieren|Intelligenter Kontrast|Lesemodus|Sprechen & Schreiben|Gebärdensprache (Libras)|Großes Widget|Widget verschieben|Problem melden|Welches Problem ist aufgetreten?|Ihre E-Mail (optional)|Senden|Danke! Ihre Meldung wurde an den Websitebetreiber gesendet.|Die Meldung konnte nicht gesendet werden. Bitte erneut versuchen.|Wort nachschlagen|Sprechen Sie, um ins Feld zu schreiben…|Protanopie|Deuteranopie|Tritanopie|Achromatopsie|Stimme|Tab zum Bewegen, Alt+H für Überschriften, Strg+K zum Pausieren.",
'it': "Daltonismo|Scala dei contenuti|Contrasto intelligente|Modalità lettura|Parla e scrivi|Lingua dei segni (Libras)|Widget grande|Sposta widget|Segnala un problema|Quale problema hai riscontrato?|La tua email (facoltativa)|Invia|Grazie! La segnalazione è stata inviata al proprietario del sito.|Impossibile inviare la segnalazione. Riprova.|Cerca una parola|Parla per scrivere nel campo…|Protanopia|Deuteranopia|Tritanopia|Acromatopsia|Voce|Premi Tab per spostarti, Alt+H per i titoli, Ctrl+K per mettere in pausa.",
'pt': "Daltonismo|Escala do conteúdo|Contraste inteligente|Modo de leitura|Falar e digitar|Língua de sinais (Libras)|Widget grande|Mover widget|Relatar um problema|Qual problema você encontrou?|Seu e-mail (opcional)|Enviar|Obrigado! Seu relato foi enviado ao dono do site.|Não foi possível enviar. Tente novamente.|Procurar uma palavra|Fale para digitar no campo…|Protanopia|Deuteranopia|Tritanopia|Acromatopsia|Voz|Pressione Tab para navegar, Alt+H para títulos, Ctrl+K para pausar.",
'nl': "Kleurenblindheid|Inhoud schalen|Slim contrast|Leesmodus|Spreken en typen|Gebarentaal (Libras)|Grote widget|Widget verplaatsen|Probleem melden|Welk probleem heeft u gevonden?|Uw e-mail (optioneel)|Verzenden|Bedankt! Uw melding is naar de website-eigenaar gestuurd.|Melding kon niet worden verzonden. Probeer het opnieuw.|Woord opzoeken|Spreek om in het veld te typen…|Protanopie|Deuteranopie|Tritanopie|Achromatopsie|Stem|Druk op Tab om te navigeren, Alt+H voor koppen, Ctrl+K om te pauzeren.",
'pl': "Daltonizm|Skalowanie treści|Inteligentny kontrast|Tryb czytania|Mów i pisz|Język migowy (Libras)|Duży widżet|Przenieś widżet|Zgłoś problem|Jaki problem napotkałeś?|Twój e-mail (opcjonalnie)|Wyślij|Dziękujemy! Zgłoszenie wysłano do właściciela strony.|Nie udało się wysłać zgłoszenia. Spróbuj ponownie.|Wyszukaj słowo|Mów, aby pisać w polu…|Protanopia|Deuteranopia|Tritanopia|Achromatopsja|Głos|Naciśnij Tab, aby się poruszać, Alt+H dla nagłówków, Ctrl+K, aby wstrzymać.",
'tr': "Renk körlüğü|İçerik ölçekleme|Akıllı kontrast|Okuma modu|Konuş ve yaz|İşaret dili (Libras)|Büyük pencere|Pencereyi taşı|Sorun bildir|Hangi sorunu yaşadınız?|E-postanız (isteğe bağlı)|Gönder|Teşekkürler! Bildiriminiz site sahibine gönderildi.|Bildirim gönderilemedi. Lütfen tekrar deneyin.|Kelime ara|Alana yazmak için konuşun…|Protanopi|Döteranopi|Tritanopi|Akromatopsi|Ses|Gezinmek için Tab, başlıklar için Alt+H, duraklatmak için Ctrl+K tuşlarına basın.",
'ru': "Дальтонизм|Масштаб контента|Умный контраст|Режим чтения|Говорите и печатайте|Жестовый язык (Libras)|Крупный виджет|Переместить виджет|Сообщить о проблеме|С какой проблемой вы столкнулись?|Ваш e-mail (необязательно)|Отправить|Спасибо! Сообщение отправлено владельцу сайта.|Не удалось отправить. Попробуйте ещё раз.|Найти слово|Говорите, чтобы вводить текст в поле…|Протанопия|Дейтеранопия|Тританопия|Ахроматопсия|Голос|Tab — перемещение, Alt+H — заголовки, Ctrl+K — пауза.",
'ar': "عمى الألوان|تحجيم المحتوى|تباين ذكي|وضع القراءة|تحدث واكتب|لغة الإشارة (Libras)|أداة كبيرة|نقل الأداة|الإبلاغ عن مشكلة|ما المشكلة التي واجهتها؟|بريدك الإلكتروني (اختياري)|إرسال|شكرًا! تم إرسال بلاغك إلى مالك الموقع.|تعذر إرسال البلاغ. حاول مرة أخرى.|ابحث عن كلمة|تحدث للكتابة في الحقل…|عمى الأحمر|عمى الأخضر|عمى الأزرق|عمى الألوان الكلي|الصوت|اضغط Tab للتنقل، وAlt+H للعناوين، وCtrl+K للإيقاف المؤقت.",
'he': "עיוורון צבעים|שינוי קנה מידה|ניגודיות חכמה|מצב קריאה|דבר והקלד|שפת סימנים (Libras)|וידג'ט מוגדל|הזזת הווידג'ט|דיווח על בעיה|באיזו בעיה נתקלת?|הדוא\"ל שלך (רשות)|שליחה|תודה! הדיווח נשלח לבעלי האתר.|לא ניתן לשלוח את הדיווח. נסו שוב.|חיפוש מילה|דברו כדי להקליד בשדה…|פרוטנופיה|דאוטרנופיה|טריטנופיה|אכרומטופסיה|קול|הקישו Tab למעבר, Alt+H לכותרות, Ctrl+K להשהיה.",
'hi': "रंग अंधता|सामग्री स्केलिंग|स्मार्ट कंट्रास्ट|पठन मोड|बोलें और लिखें|सांकेतिक भाषा (Libras)|बड़ा विजेट|विजेट खिसकाएँ|समस्या की रिपोर्ट करें|आपको कौन सी समस्या मिली?|आपका ईमेल (वैकल्पिक)|भेजें|धन्यवाद! आपकी रिपोर्ट साइट के मालिक को भेज दी गई।|रिपोर्ट नहीं भेजी जा सकी। फिर से प्रयास करें।|शब्द खोजें|फ़ील्ड में लिखने के लिए बोलें…|प्रोटानोपिया|ड्यूटेरानोपिया|ट्रिटानोपिया|एक्रोमैटोप्सिया|आवाज़|आगे बढ़ने के लिए Tab, शीर्षकों के लिए Alt+H, रोकने के लिए Ctrl+K दबाएँ।",
'zh': "色盲|内容缩放|智能对比度|阅读模式|语音输入|手语（Libras）|放大面板|移动面板|报告问题|您遇到了什么问题？|您的邮箱（可选）|发送|谢谢！您的报告已发送给网站所有者。|报告发送失败，请重试。|查词|说话即可输入到字段中…|红色盲|绿色盲|蓝色盲|全色盲|语音|按 Tab 移动，Alt+H 跳到标题，Ctrl+K 暂停。",
'ja': "色覚障害|コンテンツの拡大縮小|スマートコントラスト|リーダーモード|音声入力|手話（Libras）|ウィジェットを大きく|ウィジェットを移動|問題を報告|どんな問題がありましたか？|メールアドレス（任意）|送信|ありがとうございます。サイト運営者に報告を送信しました。|送信できませんでした。もう一度お試しください。|単語を調べる|話すと入力欄に入力されます…|1型色覚|2型色覚|3型色覚|全色盲|音声|Tab で移動、Alt+H で見出し、Ctrl+K で一時停止します。",
}

out = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'public', 'i18n')
os.makedirs(out, exist_ok=True)
for lang, blob in T.items():
    vals = [v.strip() for v in blob.replace('\n', '|').split('|')]
    assert len(vals) == len(K), (lang, len(vals), len(K))
    vals2 = [v.strip() for v in T2[lang].split('|')]
    assert len(vals2) == len(K2), (lang, 'v2', len(vals2), len(K2))
    data = dict(zip(K, vals))
    data.update(zip(K2, vals2))
    with open(os.path.join(out, lang + '.json'), 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=0)
print('wrote', len(T), 'languages,', len(K) + len(K2), 'keys each')
